<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DacPCGkim" failures="1" tests="1" name="Verify that the new case will be created by patient" time="126.021" errors="0" timestamp="2022-08-10T12:20:53 ICT">
  <testcase classname="com.scripts.MDL_patient" name="MDL_patient_new_case" time="117.235">
    <failure type="java.io.FileNotFoundException" message="src\test\resources\MDL.xlsx (The process cannot access the file because it is being used by another process)">
      <![CDATA[java.io.FileNotFoundException: src\test\resources\MDL.xlsx (The process cannot access the file because it is being used by another process)
at java.base/java.io.FileOutputStream.open0(Native Method)
at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:123)
at com.frame.ExcelHelpers.setCellData(ExcelHelpers.java:110)
at com.scripts.MDL_patient.MDL_patient_new_case(MDL_patient.java:74)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- MDL_patient_new_case -->
  <testcase classname="com.scripts.MDL_patient" name="MDL_patient_to_approve" time="0.0">
    <ignored/>
  </testcase> <!-- MDL_patient_to_approve -->
  <testcase classname="com.scripts.MDL_patient" name="complete" time="0.0">
    <ignored/>
  </testcase> <!-- complete -->
  <testcase classname="com.scripts.MDL_patient" name="MDL_patient_to_assign" time="0.0">
    <ignored/>
  </testcase> <!-- MDL_patient_to_assign -->
</testsuite> <!-- Verify that the new case will be created by patient -->
